# Generated by Django 3.2.3 on 2021-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('category', models.CharField(max_length=200, verbose_name='Категория услуг')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
