# Generated by Django 3.2.4 on 2021-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
