# Generated by Django 3.2.4 on 2021-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_auto_20210620_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
